[package]
name = "fantastic-rust-adventure"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "^0.15", features = [ "v3_20", ] }
#chrono = "0.4"
#futures = "0.3"
#futures-util = "0.3"
once_cell = "1.2.0"

#serde = { version = "1.0", features = [ "derive" ] }
